default:
    trainer: sac
    batch_size: 128
    buffer_size: 50000
    buffer_init_steps: 0
    hidden_units: 128
    init_entcoef: 1.0
    learning_rate: 3.0e-4
    learning_rate_schedule: constant
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_update: 1
    train_interval: 1
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    tau: 0.005
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99


Imitator:
    trainer: sac
    batch_size: 128
    buffer_size: 200000
    buffer_init_steps: 5000
    hidden_units: 256
    init_entcoef: 1.0
    learning_rate: 5.0e-4
    learning_rate_schedule: constant
    max_steps: 6.0e6
    memory_size: 32
    normalize: true
    num_update: 1
    train_interval: 5
    num_layers: 2
    time_horizon: 64
    sequence_length: 128
    summary_freq: 1000
    tau: 0.005
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.1
            gamma: 0.99
            encoding_size: 128
